services:
  - type: static
    name: wista-project
    env: static
    buildCommand: bun install && bun run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
